### ISSUE TITLE
MUT allows import of email address with spaces and other illegal characters

### ISSUE THREAD

**Issue by AJErazzor** [jamf/mut#73]
Takes the import literally - should fail and log if there are spaces in a computer or device assigned user.  Im sure that it also used to check if the user existed in LDAP as well

**Comment by mike-levenick** [comment]
I'm a bit torn on this one, because if the API accepts the data, I'm not sure if MUT should be limiting what we can do with the API. 

Do you get an API error when submitting the invalid data? Or does the API accept it?

As for the LDAP stuff, if you have the LDAP sync option checked under inventory updates in Jamf Pro settings, then LDAP syncing will happen on inventory update. So you can assign a username to a device with MUT and then the next time that device checks in, Jamf Pro will pull other data (like full name, etc) from that LDAP record and put it on the device.
