### ISSUE TITLE
Authentication Method: Bearer Tokens

### ISSUE THREAD

**Issue by henrytak** [jamf/mut#82]
Does MUT use bearer tokens?  The readme says it gets a token, so I am ASSuming it is using bearer tokens.  Need to know so can inform security teams.  Thanks

**Comment by mike-levenick** [comment]
Yep, bearer tokens are utilized.

More specifically, basic auth is performed using a base64 encoding of the
provided credentials, which is stored and also used to gather a token.

The token is then used on any API calls performed to the new JPAPI, while
the basic auth encoded credentials are used for calls against the classic
API.

I believe the classic API also now supports token auth, and I will likely
be updating MUT in the not-too-distant future to utilize this, and revamp
token management (auto renewal on expiry etc).

**Comment by henrytak** [comment]
Thank you sir.   You are a scholar and a gentlemen.

Thanks


------------------------------------------------
Henry Takayoshi
________________________________

**Comment by staze** [comment]
Hey @mike-levenick any update on this? we're wanting to turn off the old basic auth and MUT still seems to use for classic API. 

Thanks!

**Comment by cdenesha** [comment]
I asked a Jamf friend to check with @mike-levenick to determine how we are going to proceed. We do NOT want this beautiful tool to be useless!!

chris

**Comment by mikelevenick** [comment]
Hey folks. @mike-levenick (@mikelevenick) here. 

I have some code written to support this. It's been written for a while, actually, it's just sorta been sitting as life got kinda crazy. Thanks for letting me know about the basic auth removal--I knew we were planning to do it, but didn't realize it was going completely away soon.

You may or may not know that Jamf has "adopted" MUT, so it is now officially a Jamf product. That means I have to jump through some hoops that I'm not used to jumping through in order to get things signed/released and all that. I'm working on those hoops now to get you an "official" version.

In the mean-time, if you'd like to try out the new version in beta, you can find it here: https://github.com/jamf/mut/tree/release/6.2 and simply clone down the project and build it in XCode and give it a shot.

Quite a few changes here. All settings have been centralized to a new menu, located under MUT > Settings in the menu bar (Command + comma will also open it). Here you can access features such as log level, open your log, comma vs semicolon delimiter, usernames-as-ints, etc. 

Additionally, I am no longer using defaults to store usernames and server info. Server info, user, and password are now securely stored all together in Keychain. There is a legacy option available in settings to use defaults to store username and server URL via defaults still, but storing passwords is not available in this way.

If you do store user/password in keychain, there's also an option to use that info to auto-login when launching the app. MUT will detect stored credentials, and use them to authenticate, taking you directly to the 'home' screen, and bypassing the need to login altogether. This is an additional option, and doesn't need to be used if you're storing user/password in keychain.

Finally, all API calls are handled with bearer tokens now, so there is full support for the deprecation of basic auth. Note that user and password are still required, as that is how the bearer tokens are generated.

Let me know if you have any questions, and if there's any information I can provide. 

If you are able to download and test the build, I'd very much appreciate it. I obviously do as much testing as I can, but often things are found in the 'real world' that I cannot account for.

Thanks!

**Comment by mikelevenick** [comment]
@cdenesha thanks so much for that, that's actually a huge help! We've got a version cut now, and are in the process of getting it to the app store for release. 

I think that's a good idea with the default log level. I got bit by that myself actually. I'll see how much of a lift that woudl be to change before getting it shipped.

Thanks again, and great work on getting it built. MUT was my transition from scripter to developer myself. :)

**Comment by chrisgzim** [comment]
> Hi Mike,
> 
> I just cloned the project and built/ran it. I'm a scripter, not a developer, so the build process was unfamiliar to me. But I set up an Account in Xcode and it worked.
> 
> I can confirm that The MUT 6.2 does work against the latest Jamf Pro Cloud 11.32 with bearer tokens! I turned off "Allow Basic authentication" on the test server and am still able to update multiple devices. :)
> 
> FYI, you might want to set the default setting for log level to 'Info' like we are used to..
> 
> Let me know if there is anything specific you'd like me to test. I'll do some more testing, then cautiously proceed with 6.2 on my production server..
> 
> thank you,
> 
> chris

Hey Chris! I just submitted a PR to update the Log Level and it will be in the next version that we release: 

https://github.com/jamf/mut/commit/7be1fbfcf78373df6cc1f5afdddb7c196f7c920e

**Comment by mikelevenick** [comment]
6.2.0 has shipped, marking closed!
