### ISSUE TITLE
Logging details needs more info

### ISSUE THREAD

**Issue by jwoll** [jamf/mut#85]
When adding mobile devices to a static group, the initial method fails, and there's no output or information on which line, device, or attribute it failed on. It would be helpful to have this information present in the log in order to remove the corrupt data to proceed with the upload.

This would be especially helpful when uploading a large number of devices so the time spent using the line-by-line method isn't wasted. Thank you!

**Comment by mikelevenick** [comment]
Hey @jwoll , I think the new "classic mode fallback" will solve this for you even better.

Basically, if the initial upload fails because of a failed line or two, it will default to uploading the lines one at a time. This is far slower, but it will only fail on the 'bad' lines, which can then be found in the log. All "good" lines will be run.
